// Calendar-specific types for Studex Smart Study Calendar

export type CalendarView = 'month' | 'week' | 'day';

export type StudyPriority = 'Low' | 'Medium' | 'High';

export type TaskStatus = 'todo' | 'in-progress' | 'completed' | 'missed' | 'cancelled';

export type StudyStatus = 'planned' | 'completed' | 'partial' | 'missed' | 'none';

export interface StudyPlan {
  id: string;
  date: string; // ISO date string "YYYY-MM-DD"
  subjectName: string;
  chapterName: string;
  pageStart: number;
  pageEnd: number;
  estimatedMinutes: number;
  priority: StudyPriority;
  notes?: string;
  createdAt: string;
  // New fields for Smart Calendar
  status?: TaskStatus;
  subjectId?: string;
  chapterId?: string;
  isAutoGenerated?: boolean;
}

export interface StudySession {
  id: string;
  date: string; // ISO date string "YYYY-MM-DD"
  planId?: string; // linked plan if any
  subjectName: string;
  chapterName: string;
  pagesCompleted: number;
  pageStart: number;
  pageEnd: number;
  minutesStudied: number;
  notes?: string;
  completedAt: string;
  subjectId?: string;
  chapterId?: string;
}

export interface CalendarDayData {
  date: string; // "YYYY-MM-DD"
  plans: StudyPlan[];
  sessions: StudySession[];
  status: StudyStatus;
  totalPlannedMinutes: number;
  totalStudiedMinutes: number;
  completionPercent: number;
  totalPlannedPages: number;
  totalCompletedPages: number;
  studyStreak: number;
}

export interface MissedTaskAction {
  planId: string;
  action: 'tomorrow' | 'reschedule' | 'cancel' | 'redistribute';
  newDate?: string;
}
